### ISSUE TITLE
error when loading dataset

### ISSUE THREAD

**Issue by twangnh** [bethgelab/siamese-mask-rcnn#18]
Hi @michaelisc there is an error while loading dataset, could you pls take a look
```
ssh://wangtao@deep41:22/home/wangtao/anaconda2/envs/tensorflow_/bin/python -u /home/wangtao/.pycharm_helpers/pydev/pydevd.py --multiproc --qt-support=auto --client '0.0.0.0' --port 37213 --file /home/wangtao/prj/siamese_mrcnn/train.py
pydev debugger: process 15874 is connecting

Connected to pydev debugger (build 181.4892.64)
Using TensorFlow backend.


loading annotations into memory...
Done (t=26.20s)
creating index...
index created!
Traceback (most recent call last):
  File "/home/wangtao/.pycharm_helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/wangtao/.pycharm_helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/wangtao/.pycharm_helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/wangtao/prj/siamese_mrcnn/train.py", line 35, in <module>
    coco_train.build_indices()
  File "/home/wangtao/prj/siamese_mrcnn/lib/utils.py", line 328, in build_indices
    self.category_image_index = IndexedCocoDataset._build_category_image_index(self.image_category_index)
TypeError: unbound method _build_category_image_index() must be called with IndexedCocoDataset instance as first argument (got list instance instead)

```

**Comment by michaelisc** [comment]
Could you provide the code you executed? From the error message I am not sure, what went wrong.

**Comment by twangnh** [comment]
turns out it is caused by python version, I was using py2, change to py3 works
